version: "3.9"

x-test-framework: pytest

x-service:
  &service
  build:
    context: .
  volumes:
    - type: volume
      source: output
      target: $ENGI_WORKING_DIR

services:
  format:
    command: black src/
    <<: *service
  tests:
    command: pytest -s --report-log $ENGI_WORKING_DIR/pytest.json
    <<: *service
    depends_on:
      - format
volumes:
  output:
    external: true
    name: $ENGI_WORKING_VOL
